### ISSUE TITLE
move the inner circle to where i press even when outside of Background

### ISSUE THREAD

**Issue by grenzionky** [MarcoFazioRandom/Virtual-Joystick-Godot#2]
is there a way to make it so that the the joysticks inner circle (the one that u move around) goes to the direction where i click even if i click outside of the Background?

**Comment by grenzionky** [comment]
i got it. i made a small edit to the file

**Comment by MarcoFazioRandom** [comment]
First of all sorry for the late response.
I already responded in your pull request, but I really don't like when I click outside of the Joystick and my character starts to move because the joystick read my touch as an input even if I didn't touch it, I designed it like this so the joystick is more precise.
