### ISSUE TITLE
Use standard addons structure

### ISSUE THREAD

**Issue by fire** [MarcoFazioRandom/Virtual-Joystick-Godot#48]
Hi, I was wondering if you can move the layout into the standard "addons/Virtual-Joystick-Godot" structure for the redistributable and use the outside structure for demos.

The folders in your project may collide with other file paths. We only use 3 folders in our project. 

1. addons
2. \<project_utils>
3. \<project>

Note:

Typically it's "addons/virtual_joystick_godot" in the Godot Engine style guide, but it's no big deal.

**Comment by MarcoFazioRandom** [comment]
Hello, 
Thanks for pointing this out, I didn't know about this. I will study the standard structure and edit the project accordingly.

**Comment by LucasArusiewicz** [comment]
I don't know if you've already looked at this link, I hope it helps.
The good thing is it shows how to configure and change the plugin icon.
[Making plugins](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html)

**Comment by lfkdev** [comment]
@MarcoFazioRandom did you had the time to look into it? if people download this from the asset library right now it overwrites their whole project. this is not how plugins work

**Comment by MarcoFazioRandom** [comment]
Sorry for the (very) late reply, I'm working on this project in my spare time.

Imho the Godot documentation is not very clear on how to make a plugin  from a scene (that's why I had to make the virtual_joystick_instantiator script, not sure if it's the cleanest solution but it works).

I created the Plugin branch to use the addons structure, will wait for a few feedback and make it the main branch if everything is correct.
